---
# tasks file for pycharm

- name: install tar on Fedora 24
  dnf:
    name: tar
    state: present
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "24"

- name: Create directories for phpstorm
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ phpstorm_download_directory }}"
  - "{{ phpstorm_install_directory }}"
  - "{{ phpstorm_desktop_file_location | dirname }}"


- name: Download phpstorm plugins
  get_url:
    url: "{{ phpstorm_plugin_download_mirror }}{{ item }}"
    dest: "{{ phpstorm_download_directory }}"
  register: phpstorm_plugins_downloaded
  with_items: "{{ phpstorm_plugins }}"

- name: Install PhpStorm
  unarchive:
    src: "{{ phpstorm_download_url}}"
    dest: "{{ phpstorm_download_directory }}"
    copy: no
    list_files: yes
    creates: "{{ phpstorm_location }}/bin/phpstorm.sh"
  register: unarchive_phpstorm

- name: Find PhpStorm build number
  set_fact:
    phpstorm_buildnumber: "{{ unarchive_phpstorm.files[0].split('/')[0] }}"
  when: unarchive_phpstorm|changed
  tags:
    - skip_ansible_lint

- debug:
    msg: "Build number: {{ phpstorm_buildnumber }}"
  when: unarchive_phpstorm|changed
  tags:
    - skip_ansible_lint

- name: Move to final location
  command: mv {{ phpstorm_download_directory }}/{{ phpstorm_buildnumber }} {{ phpstorm_location }}
  when: unarchive_phpstorm|changed
  tags:
    - skip_ansible_lint

- name: Install phpstorm Plugins
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ phpstorm_location }}/plugins"
  with_items: "{{ phpstorm_plugins_downloaded.results }}"

- name: Create phpstorm desktop entry
  template:
    src: phpstorm.desktop.j2
    dest: "{{ phpstorm_desktop_file_location }}"
